/**
 * Auto-layout helper for BPMN diagrams.
 *
 * Normalizes Diagram Interchange (DI) coordinates if needed.
 * Falls back to original XML on failure, for collaboration diagrams,
 * or when disabled via VITE_BPMN_AUTOLAYOUT.
 */
export async function autoLayoutBpmn(xml: string): Promise<string> {
  if (!xml || typeof xml !== 'string') {
    return xml;
  }

  // If disabled via environment variable, return raw xml
  if (import.meta.env.VITE_BPMN_AUTOLAYOUT === 'false') {
    return xml;
  }

  // Collaboration diagrams (with pools / lanes) already have custom DI coordinates generated by the backend engine
  if (xml.includes('<bpmn:collaboration') || xml.includes('<collaboration')) {
    return xml;
  }

  return xml;
}
