spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    ollama:
      chat:
        enabled: false
    openai:
      api-key: dummy_key_to_satisfy_client_init
      chat:
        enabled: false
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash
            temperature: 0.1
            max-tokens: 2048